### ISSUE TITLE
Missing LD686 Controller

### ISSUE THREAD

**Issue by Arsur** [xylo/openhab2-addons#1]
Maybe you can add the missing LD686 Controller?
Its working like an LD382A with just an channel more. Iam a total noob in creating a Openhab binding, thats why iam asking :|

I did some reseach and openend [**this**](https://community.openhab.org/t/wifiled-wifilight-binding/16739/7) conversion at the Openhab Board. One user did an interesting modification...

**Comment by xylo** [comment]
Oh, interesting.  Looks like the 5th channel is a cold white channel.  Yeah, I can add this.

When it's implemented I release a jar file as long as this addon is not available via openHAB2.

**Comment by davearias** [comment]
I'm the one using the binding with the tweak for the 5th channel. I can test once it's available.

**Comment by xylo** [comment]
OK, it's implemented.  At the moment channel 5 is always 0.

If you like, you can download the latest version [here](http://stefan.endrullis.de/openhab2/org.openhab.binding.wifiled-2.0.0-SNAPSHOT.jar).

**Comment by davearias** [comment]
Just loaded it. Looks to be working properly!

**Comment by davearias** [comment]
I take that back. It might not be dimming, only the ON/OFF functionality might be working. I'll have to test more.

**Comment by bbruno84** [comment]
Hi everybody, sorry but I'm new to github and openhab and i don't have good programming skills, but i tested the last version for the LD686 protocol that was posted here on 1st dec. Like davearias says, it doesn't works (only the power switch it's working). but after some debugging i figured out that the "command" to change the color is not 0x61 but it's 0x31. The protocol used is the LD382a (after adding the 5th channel, w2). In the attached zip you will find the compiled binding and the 2 files that i have edited. Please fix it well, not as I do :)

[LD686.zip](https://github.com/xylo/openhab2-addons/files/679769/LD686.zip)

**Comment by xylo** [comment]
@bbruno84
Thanks for your changes.  I ordered an LD686 controller, too.  I hope it's coming next week.  Then I will continue working on the binding.

**Comment by tilou** [comment]
Hi all and thanks for writing the wifilight binding :-) 
I´am completely new to openhab and would like to use the binding. I have an openhabian installation up and running and some basic shell knowledge but no idea about all this java stuff. :-( Still got the dec 01 snapshot installed. 

I got one of these wifiled controllers and would like to integrate them into openhab.  
http://www.banggood.com/ARILUX-AL-LC02-Super-Mini-LED-WIFI-APP-Controller-Dimmer-for-RGBW-LED-Strip-Light-DC-9-12V-p-1060222.html?p=UR1110667020201407CM

According to this page: http://jbmedia.eu/forum/viewtopic.php?f=21&t=331
the device has a LD382.

Can anyone tell me if this is supported and how to integrate it into the system. 
How can I find out more about the controller? 
It is already running with the magic home app, so it should be in the same network. 
All hints and advice welcome!

PS: please also correct me if this is not the right spot for such a demand.

**Comment by Arsur** [comment]
I have this one already running in my system. Put the Binding Jar File in to the addon folder of OH. Than restart OH and if its not already discovered, start a device discovery in the PaperUI. I think it uses an LD382A. But the Binding configures it by it self.

By the way its alot cheaper on Aliexpress

**Comment by tilou** [comment]
Thanks and good to know Arsur. 
The binding is ok. Its the 2.0.0. snapshot and I can find it in paper ui.
Discovery did not work :-( 
Is this device treated as a bridge? 
I configured it manually with the corresponding IP and I had some effects on the LED stripe. But there are so many things I dont know which one is relevant. 
Currently I have only connected a white LED stripe to channel W. 
Here is what I did: Inbox -> choose Milight Binding -> Search -> Nothing detected. 
I add a bridge manually and enter the IP. 11 things are then dicovered. 

Any idea how to use them?

**Comment by Arsur** [comment]
Mhm i dont understand why you use the Milight Binding. You need the WifiLed Binding. You should read these two conversations. https://github.com/openhab/openhab2-addons/issues/496 and 
https://community.openhab.org/t/wifiled-wifilight-binding/16739
I hope they help you?

**Comment by tilou** [comment]
Uhh very good advice. 
Ok so the binding is not successfully installed. 

How can check whats going wrong?
I have put "org.openhab.binding.wifiled-2.0.0-SNAPSHOT.jar" 
to the directory /usr/share/openhab2/addons$ and restartet with 
"sudo service openhab2 restart"

Nothing in the bindings list. How can I check if anything has been installed? 

Does the .jar file need to be executable? 
-rw-r--r-- 1 openhab openhab 37407 Jan 18 01:38 org.openhab.binding.wifiled-2.0.0-SNAPSHOT.jar

**Comment by Arsur** [comment]
Your user rights should work. Your device and the openhab server are in the same network?
You can use the Karaf console. http://docs.openhab.org/administration/console.html i think bundle:list should show you if its even found from openhab and if its loaded or whats the status of it
In my case the paperui shows me the Binding under configuration --> Bindings

**Comment by tilou** [comment]
Success! 
Its up and running. Great job and a big "thank you" for making this binding! Excellent!
 
A wonder has happend overnight. Sometimes "things" need time to mature and newbies to openhab need some sleep. I made a terrible mistake yesterday. I was fine with my  ssh client on the right box. 
I was on a different old installation on my synology with paper UI - No wonder the plugin was not installed!

So thanks to all you great helpers!   
Thanks also to Arsur for the console link. I will have a look at this. Great evening to all!

**Comment by xylo** [comment]
@tilou 
I'm pleased that it works.

@Arsur
Thanks for your help.

@both of you
Thanks and for the tip regarding the Arilux LED controllers.  I didn't know them by now, but that's exactly what I was looking for.  It's smaller and cheaper than my current controllers. Moreover, it doesn't have the annoying status LEDs, but it has a 5-pin-port to directly plug in the LED strip. Great work! :)

**Comment by Arsur** [comment]
I can recommend you this seller [Aliexpress Link](https://www.aliexpress.com/item/Wifi-LED-RGB-Controler-DC12V-MIni-Wifi-RGB-RGBW-LED-Controller-for-RGB-RGBW-LED-Strip/32730917303.html?spm=2114.13010608.0.0.Rjapoh)
It was send to germany in 2 weeks over Xmas.
But I kind of like the LD686 because of the nice mounting brakets for the Led Wires (but most of the time i solder and build up my lights by my self, so thats maybe only interesting for me)

**Comment by xylo** [comment]
OK, the LD686 support works now.  [Here](http://stefan.endrullis.de/openhab2/org.openhab.binding.wifiled-2.0.0-SNAPSHOT.jar) is the new version of the addon.

@Arsur
Thanks for the link.  I ordered one. :)

**Comment by xylo** [comment]
@bbruno84 
Does this version also work for you?  When you want to test it you have to change the protocol in your thing configuration to LD686 now.

I reviewed all your changes and also tried to change the color command from 0x61 to 0x31, but this did not work with my LD686 controller.  I wonder if there are different versions of it.  The Magic Home WiFi App tells me I have a "v1".

**Comment by bbruno84** [comment]
@xylo 
This version works out of the box.
I have this controller https://www.amazon.it/Regolatore-Striscia-Wireless-regolazione-Smartphone/dp/B01J5A7ABW/ref=sr_1_2?ie=UTF8&qid=1485202255&sr=8-2&keywords=wifi+led+controller
The Magic Home app tells me v1, too

**Comment by xylo** [comment]
@bbruno84 
I'm glad that it works for you, too.  Thanks for the info.

So, I would say the LD686 support is implemented.
